version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3.4
        environment:
          BUNDLE_PATH: '/home/ubuntu/shared_bundle'
          RAILS_ENV: test
    working_directory: /home/ubuntu/publisher
    steps:
      - checkout
      - restore_cache:
          key: publisher-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Gems
          command: |
            mkdir -p $BUNDLE_PATH
            bundle install
      - save_cache:
          key: publisher-{{ checksum "Gemfile.lock" }}
          paths:
            - "/home/ubuntu/shared_bundle"
      - run:
          name: Run Specs
          environment:
            RAILS_ENV: 'test'
          command: |
            SPEC_FILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            echo $RSPEC_FILES
            bundle exec rspec \
              --profile=5 \
              --fail-fast=5 \
              --order random \
              --format documentation \
              --color \
              --require spec_helper \
              --format RspecJunitFormatter \
              --out ~/rspec/rspec.xml -- $RSPEC_FILES
